# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88dd9c391ab1c48cfbeba2211a3f700a3fef5cc161ac4331c415c84609e603f110bc5e54351a45692443aa859069e4b4ad6c584f6bcb07693ec387fe63f2f840

test:
  secret_key_base: 5862ed276e8f808c9f2baddc8cdde98b8ed83eec709e54399e000104941b57d70926a803538dc7339c1f0e8df5bd53aaaaf8c31029c6dee9f78ef79d26d45683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
